import { useMemo, useState } from "react";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { ArrowRight, CalendarDays, Check, CheckCircle2, Info, Leaf, MapPin, PackageCheck, Warehouse } from "lucide-react";
import { BackButton } from "@/components/BackButton";
import { DateAvailability, getDateAvailability, getDateRange, parseDateLabel, useAuth } from "@/context/AuthContext";
import { farmer } from "@/data/mockData";

const availabilityCopy: Record<DateAvailability, { label: string; className: string }> = {
  Available: { label: "Slots available", className: "token-date-available" },
  "Filling Fast": { label: "Filling fast", className: "token-date-filling" },
  Full: { label: "Full — book another day", className: "token-date-full" },
};

export default function BookToken() {
  const { currentUser, slot, centres, policy, records, tokens, requestToken } = useAuth();
  const navigate = useNavigate();
  const centre = centres.find((item) => item.id === slot.centreId) || centres[0];
  const remainingEligible = Math.max(0, farmer.verifiedLandArea * policy.procurementLimitPerAcre - records.reduce((sum, record) => sum + record.quantity, 0));
  const dateOptions = useMemo(() => getDateRange(slot.startDate, slot.endDate).filter((date) => parseDateLabel(date) > parseDateLabel("21 Mar 2024")), [slot.startDate, slot.endDate]);
  const [step, setStep] = useState(1);
  const [selectedDate, setSelectedDate] = useState("");
  const [quantity, setQuantity] = useState(Math.min(40, remainingEligible));
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [confirmedToken, setConfirmedToken] = useState<string | null>(null);
  const isExpired = parseDateLabel("21 Mar 2024") > parseDateLabel(slot.endDate);
  const quantityError = quantity <= 0 ? "Enter an expected quantity greater than zero." : quantity > remainingEligible ? `You can request up to ${remainingEligible} quintals, your remaining eligible quantity.` : "";

  if (!currentUser || currentUser.role !== "farmer") return <Navigate to="/login/farmer" replace />;

  const goToStep = (nextStep: number) => { setError(""); setStep(nextStep); };
  const handleBack = () => { if (step > 1) { goToStep(step - 1); return; } if ((selectedDate || quantity !== Math.min(40, remainingEligible)) && !window.confirm("Discard this booking and go back?")) return; navigate(-1); };
  const chooseDate = (date: string, status: DateAvailability) => { if (status === "Full") return; setSelectedDate(date); setError(""); goToStep(2); };
  const submitToken = () => { if (!centre || !selectedDate) { setError("Choose a visit date to continue."); return; } if (quantityError) { setError(quantityError); return; } setSubmitting(true); const result = requestToken({ farmerId: farmer.id, centreId: centre.id, requestedDate: selectedDate, expectedQuantity: quantity }); setSubmitting(false); if (!result.ok || !result.token) { setError(result.error || "Could not request a Token."); return; } setConfirmedToken(result.token.shortReference); };

  if (slot.status !== "Active" || isExpired || remainingEligible <= 0) {
    const message = slot.status !== "Active" ? "You need an active Slot before booking a Token." : isExpired ? "Your Slot has expired. Please book a new Slot." : "You have no remaining eligible quantity to procure.";
    return <div className="booking-page"><div className="demo-mode-banner" role="status">Demo Mode · Simulated data for SIH26032 prototype</div><div className="tricolor" /><main className="booking-wrap"><BackButton to="/" /><div className="booking-success booking-gate" role="alert"><div className="success-check"><Info size={32} /></div><span className="eyebrow">TOKEN BOOKING</span><h1>{message}</h1><p>{slot.status !== "Active" || isExpired ? "Start a new Slot before choosing a warehouse visit." : "Your eligible quantity has already been allocated."}</p>{(slot.status !== "Active" || isExpired) && <Link className="primary-button" to="/farmer/book-slot">Book a New Slot <ArrowRight size={16} /></Link>}<button className="outline-button" onClick={() => navigate("/")}>Back to Dashboard</button></div></main></div>;
  }

  if (confirmedToken) return <div className="booking-page"><div className="demo-mode-banner" role="status">Demo Mode · Simulated data for SIH26032 prototype</div><div className="tricolor" /><main className="booking-wrap"><BackButton to="/" label="Back to dashboard" /><div className="booking-success" role="status"><div className="success-check"><Check size={35} /></div><span className="eyebrow">TOKEN REQUEST SENT</span><h1>Your Token request is under review</h1><p>The Procurement Officer will review your request and notify you once it is approved.</p><div className="success-details"><div><span>Token reference</span><strong>{confirmedToken}</strong></div><div><span>Requested date</span><strong>{selectedDate}</strong></div><div><span>Status</span><strong className="success-reference">Waiting for Approval</strong></div></div><div className="success-reference"><CheckCircle2 size={15} /> Keep your Kisaan Code ready for your approved visit.</div><div className="success-actions"><button className="primary-button" onClick={() => navigate("/")}>Track Status <ArrowRight size={16} /></button><button className="outline-button" onClick={() => navigate("/")}>Back to Dashboard</button></div></div></main></div>;

  return <div className="booking-page"><div className="demo-mode-banner" role="status">Demo Mode · Simulated data for SIH26032 prototype</div><div className="tricolor" /><header className="booking-header"><div className="booking-wrap booking-header-inner"><Link to="/" className="booking-brand"><div className="auth-emblem"><Leaf size={24} /></div><strong>ई-उपार्जन <span>e-Uparjan</span></strong></Link><span className="booking-user">{farmer.name} · {farmer.kisaanCode}</span></div></header><main className="booking-wrap"><BackButton onClick={handleBack} /><div className="booking-title"><div><span className="eyebrow">FARMER SERVICES</span><h1>Book a Token</h1><p>Choose a visit date within your active 9-day Slot.</p></div><div className="step-progress" aria-label="Token booking progress">{["Date", "Quantity", "Confirm"].map((label, index) => { const number = index + 1; return <div className={step >= number ? "step active" : "step"} aria-current={step === number ? "step" : undefined} key={label}><span>{step > number ? <Check size={13} /> : number}</span><small>{label}</small></div>; })}</div></div>{error && <div className="booking-error" role="alert"><Info size={16} /><span>{error}</span></div>}<div className="booking-grid"><section className="booking-card">
    {step === 1 && <div className="booking-step"><span className="step-kicker">STEP 1 OF 3</span><h2>Select your visit date</h2><p className="step-copy">Choose one day from your active Slot. Today is unavailable because Tokens must be booked one day before the visit.</p><div className="token-slot-summary"><CalendarDays size={20} /><div><span>Active Slot validity</span><strong>{slot.startDate} — {slot.endDate}</strong></div></div><div className="token-date-grid">{dateOptions.map((date) => { const status = centre ? getDateAvailability(centre.id, date, tokens, centres) : "Full"; const copy = availabilityCopy[status]; return <button key={date} type="button" disabled={status === "Full"} className={`token-date-choice ${copy.className} ${selectedDate === date ? "selected" : ""}`} onClick={() => chooseDate(date, status)}><strong>{date}</strong><span>{copy.label}</span></button>; })}</div><div className="availability-legend"><span><i className="available-dot" /> Slots available</span><span><i className="filling-dot" /> Filling fast</span><span><i className="full-dot" /> Full</span></div></div>}
    {step === 2 && <div className="booking-step"><span className="step-kicker">STEP 2 OF 3</span><h2>Enter expected quantity</h2><p className="step-copy">Your request cannot exceed the remaining eligible quantity for this season.</p><div className="quantity-callout"><PackageCheck size={22} /><div><span>Remaining eligible quantity</span><strong>{remainingEligible} quintals</strong><small>{farmer.verifiedLandArea} acres × {policy.procurementLimitPerAcre} q total eligibility</small></div></div><label className="quantity-input">Expected quantity for this visit<div><input aria-invalid={Boolean(quantityError)} type="number" min={1} max={remainingEligible} value={quantity} onChange={(event) => { setQuantity(Number(event.target.value)); setError(""); }} /><span>quintals</span></div></label>{quantityError && <div className="form-error" role="alert">{quantityError}</div>}<div className="step-actions"><button className="outline-button" onClick={() => goToStep(1)}>Back</button><button className="primary-button" onClick={() => goToStep(3)}>Review request <ArrowRight size={16} /></button></div></div>}
    {step === 3 && <div className="booking-step"><span className="step-kicker">STEP 3 OF 3</span><h2>Confirm Token request</h2><p className="step-copy">Review your warehouse visit details before sending the request.</p><div className="confirm-summary token-summary"><div><span>Procurement centre</span><strong><Warehouse size={15} /> {centre.name}</strong><small><MapPin size={13} /> {centre.address}</small></div><div><span>Date</span><strong><CalendarDays size={15} /> {selectedDate}</strong></div><div><span>Expected quantity</span><strong><PackageCheck size={15} /> {quantity} quintals</strong></div></div><div className="booking-note"><Info size={17} /><span>Your request will be reviewed by the Procurement Officer. You'll be notified once approved.</span></div><div className="step-actions"><button className="outline-button" onClick={() => goToStep(2)}>Back</button><button className="primary-button" disabled={submitting} onClick={submitToken}>{submitting ? "Sending request…" : "Confirm Token Request"} <ArrowRight size={16} /></button></div></div>}
  </section><aside className="booking-aside"><div className="aside-icon"><CheckCircle2 size={20} /></div><h3>Token booking guide</h3><ul><li>Book at least one day before your visit.</li><li>Choose a date within your active Slot.</li><li>Daily capacity updates live.</li><li>Wait for Procurement Officer approval before arriving.</li></ul><div className="aside-capacity"><span>Selected centre</span><strong>{centre.name}</strong><div className="capacity-bar"><span className="green" style={{ width: `${Math.max(5, ((centre.dailyWeighingCapacity - centre.usedDailyCapacity) / centre.dailyWeighingCapacity) * 100)}%` }} /></div></div><div className="aside-help"><strong>Need help?</strong><span>Call 1800-233-4250</span></div></aside></div></main><footer className="booking-footer"><span>e-Uparjan · Smart Procurement & Token Management System</span><span>Terms · Privacy · Sitemap · Contact · Last updated: 18 March 2024</span></footer></div>;
}
