import { useState } from "react";
import { CheckCircle2, Search } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { EmptyState, Notice, StaffLayout } from "./StaffLayout";
import { farmer, farmers } from "@/data/mockData";

export default function OperatorDashboard() {
  const { tokens, records, completeProcurement } = useAuth(); const [code, setCode] = useState(""); const [foundId, setFoundId] = useState<string | null>(null); const [actual, setActual] = useState(""); const [otp, setOtp] = useState(""); const [otpStep, setOtpStep] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const found = tokens.find((token) => token.id === foundId); const foundFarmer = found ? farmers.find((item) => item.id === found.farmerId) || farmer : farmer;
  const lookup = () => { setBusy(true); setError(""); window.setTimeout(() => { const normalized = code.trim().toLowerCase(); const token = tokens.find((item) => item.status === "Approved" && item.requestedDate === "21 Mar 2024" && (item.farmerId === "farmer-001" ? farmer.kisaanCode : "KIS-24-06118").toLowerCase() === normalized); setFoundId(token?.id || null); setError(token ? "" : "No approved token found for this Kisaan Code today."); setBusy(false); }, 500); };
  const sendOtp = () => { if (!Number(actual) || Number(actual) <= 0) { setError("Enter the actual quantity from the physical receipt."); return; } setError(""); setOtpStep(true); setNotice("Demo OTP sent to the farmer's registered mobile: 123456"); };
  const confirm = async () => { if (!found) return; setBusy(true); const result = await completeProcurement(found.id, Number(actual), otp); setBusy(false); if (!result.ok) setError(result.error || "Could not complete procurement."); else { setNotice("Procurement completed and payment marked pending."); setFoundId(null); setOtpStep(false); setCode(""); setActual(""); setOtp(""); } };
  const completed = records.filter((record) => record.otpConfirmed);
  return <StaffLayout role="operator" title="Centre Operator" subtitle="Weigh approved farmers, confirm receipts, and review completed records."><div className="staff-grid operator-grid"><section className="staff-panel wide-panel"><div className="staff-panel-header"><div><span className="eyebrow">APPROVED WEIGHING</span><h3>Find today's approved farmer</h3></div></div><div className="lookup-form"><input aria-label="Kisaan code" value={code} onChange={(e) => { setCode(e.target.value); setError(""); }} placeholder="Enter Kisaan Code e.g. KIS-24-05821" /><button className="primary-button" disabled={busy} onClick={lookup}><Search size={16} /> Search</button></div>{error && <div className="form-error" role="alert">{error}</div>}{notice && <Notice message={notice} onClose={() => setNotice("")} />}{found && !otpStep && <div className="operator-summary"><div className="summary-heading"><CheckCircle2 size={20} /><div><span className="eyebrow">APPROVED TOKEN FOUND</span><h3>{foundFarmer.name}</h3></div><span className="status-pill approved">{found.shortReference}</span></div><div className="summary-grid"><div><span>Kisaan code</span><strong>{code}</strong></div><div><span>Expected quantity</span><strong>{found.expectedQuantity} q</strong></div><div><span>Visit date</span><strong>{found.requestedDate}</strong></div></div><label>Actual weighed quantity<input type="number" value={actual} onChange={(e) => setActual(e.target.value)} /></label><button className="primary-button" onClick={sendOtp}>Send OTP</button></div>}{found && otpStep && <div className="operator-summary"><h3>Confirm farmer OTP</h3><p>Demo OTP: 123456</p><input aria-label="OTP" value={otp} onChange={(e) => setOtp(e.target.value)} placeholder="Enter 6-digit OTP" /><button className="primary-button" disabled={busy} onClick={() => void confirm()}>{busy ? "Saving…" : "Confirm completed weighing"}</button></div>}</section><section className="staff-panel"><span className="eyebrow">COMPLETED RECORDS</span><h3>Recent completed procurement</h3>{completed.length === 0 ? <EmptyState>No completed records yet</EmptyState> : completed.map((record) => <div className="record-row" key={record.id}><strong>{record.date}</strong><span>{record.quantity} q</span><span>₹{record.amount.toLocaleString("en-IN")}</span><small>{record.paymentStatus}</small></div>)}</section></div></StaffLayout>;
}
