import type { ReactNode } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { ArrowLeft, CheckCircle2, PackageCheck, ShieldCheck, X, type LucideIcon } from "lucide-react";
import { useAuth, type Role } from "@/context/AuthContext";

export function StaffLayout({ role, title, subtitle, children }: { role: Role; title: string; subtitle: string; children: ReactNode }) {
  const { currentUser, logout } = useAuth(); const navigate = useNavigate();
  if (!currentUser || currentUser.role !== role) return <Navigate to="/access-denied" replace />;
  const nav = role === "officer" ? ["Capacity Overview", "Token Queue & Batch Approval", "Alerts"] : role === "operator" ? ["Approved Weighing", "Completed Records"] : ["System Overview", "Policy Configuration", "Centre Configuration"];
  return <div className={`staff-page staff-${role}`}><div className="tricolor" /><header className="staff-header"><div className="staff-header-inner"><div className="brand-mark"><div className="emblem"><ShieldCheck size={23} /></div><div><p className="brand-kicker">Department of Food & Civil Supplies</p><h1>e-Uparjan <span>Staff Portal</span></h1></div></div><div className="staff-user"><span className="role-badge">{role === "officer" ? "Procurement Officer Portal" : role === "operator" ? "Operator Portal" : "Government / Admin Portal"}</span><strong>Logged in as: {currentUser.name}</strong><button className="text-button" onClick={logout}>Logout</button></div></div></header><main className="staff-wrap"><nav className="staff-nav" aria-label={`${title} navigation`}>{nav.map((item, index) => <span className={index === 0 ? "active" : ""} key={item}>{item}</span>)}</nav><div className="staff-breadcrumb"><button onClick={() => navigate("/roles")}><ArrowLeft size={13} /> Portal selection</button><span>/</span><strong>{title}</strong></div><div className="staff-title"><div><span className="eyebrow">{role.toUpperCase()} WORKSPACE</span><h2>{title}</h2><p>{subtitle}</p></div><span className="staff-date">Today · 21 March 2024</span></div>{children}</main><footer className="staff-footer"><span>e-Uparjan · SIH26032 Demo Mode</span><span>Terms · Privacy · Last updated: 18 March 2024</span></footer><div className="footer-helpline">Farmer Helpline <strong>1800-233-4250</strong></div></div>;
}
export function Notice({ message, error = false, onClose }: { message: string; error?: boolean; onClose?: () => void }) { return <div className={`staff-notice ${error ? "error" : "success"}`} role={error ? "alert" : "status"}><CheckCircle2 size={16} /><span>{message}</span>{onClose && <button aria-label="Dismiss notification" onClick={onClose}><X size={15} /></button>}</div>; }
export function Stat({ label, value, detail, icon: Icon, tone = "navy" }: { label: string; value: string; detail: string; icon: LucideIcon; tone?: string }) { return <div className={`staff-stat ${tone}`}><div><span>{label}</span><Icon size={18} /></div><strong>{value}</strong><small>{detail}</small></div>; }
export function EmptyState({ children }: { children: string }) { return <div className="staff-empty"><PackageCheck size={22} /><span>{children}</span></div>; }
